name: deligo_driver
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.2+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Styling
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  gap: ^3.0.1
  flutter_screenutil: ^5.9.3
  lottie: ^3.1.0

  # State Management
  flutter_riverpod: ^2.6.1

  # Form Handling
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.0.0

  # Networking
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  # Serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

  # Functional Programming
  dartz: ^0.10.1

  # Local Storage
  flutter_secure_storage: ^9.2.4

  # Connectivity
  connectivity_plus: ^6.1.4
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  ionicons: ^0.2.2
  pinput: ^5.0.1
  dotted_line: ^3.2.3
  file_picker: ^8.3.1
  collection: ^1.19.0
  google_maps_flutter: ^2.10.1
  geolocator: ^14.0.0
  location: ^8.0.0
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  package_info_plus: ^8.3.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.0.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^7.1.1
  flutter_ringtone_player: ^4.0.0+4
  vibration: ^3.1.3
  widget_to_marker: ^1.0.6
  flutter_polyline_points: ^2.1.0
  pusher_channels_flutter: ^2.4.0
  url_launcher: ^6.3.1
  circular_countdown_timer: ^0.2.4
  permission_handler: ^12.0.0+1
  app_settings: ^6.1.1
  image_picker: ^1.1.2
  path: ^1.9.1
  geocoding: ^4.0.0
  flutter_animate: 4.5.2
  fluttertoast: ^8.2.12
  rename: ^3.1.0
  shimmer: ^3.0.0
  equatable: ^2.0.7
  flutter_svg: ^2.2.0
  change_app_package_name: ^1.5.0
  dropdown_button2: ^2.3.9
  flutter_image_compress: ^2.4.0

dependency_overrides:
  geolocator_android: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  flutter_gen: ^5.7.0
  flutter_gen_runner: ^5.7.0
  json_serializable: ^6.7.1


  # Linting
  flutter_lints: ^6.0.0
  custom_lint: ^0.7.0

  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/avatars/
    - assets/lottie/
    - assets/svg/
    - assets/countries/
    - assets/vehicles/
    - assets/notification.mp3
    - assets/notification2.mp3

  fonts:
    - family: GeneralSans
      fonts:
        - asset: assets/fonts/generalsansextralight.ttf
          weight: 200
        - asset: assets/fonts/generalsanslight.ttf
          weight: 300
        - asset: assets/fonts/generalsansregular.ttf
          weight: 400
        - asset: assets/fonts/generalsansmedium.ttf
          weight: 500
        - asset: assets/fonts/generalsanssemibold.ttf
          weight: 600
        - asset: assets/fonts/generalsansbold.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/interthin.ttf
          weight: 100
        - asset: assets/fonts/interextralight.ttf
          weight: 200
        - asset: assets/fonts/interlight.ttf
          weight: 300
        - asset: assets/fonts/interregular.ttf
          weight: 400
        - asset: assets/fonts/intermedium.ttf
          weight: 500
        - asset: assets/fonts/intersemibold.ttf
          weight: 600
        - asset: assets/fonts/interbold.ttf
          weight: 700
        - asset: assets/fonts/interextrabold.ttf
          weight: 800
        - asset: assets/fonts/interblack.ttf
          weight: 900

flutter_gen:
  assets:
    enabled: true
  integrations:
    lottie: true

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated